GET http://127.0.0.1:8000/


###

GET http://127.0.0.1:8000/health_check

###
POST http://localhost:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin&email=ursula_le_gun%40gmail.com


###
POST https://zero2prod-wpckf.ondigitalocean.app/subscriptions
Content-Type: application/x-www-form-urlencoded

name=pandula&email=pandula%40gmail.com